language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master
